In [23]:
import os
import numpy as np
from numpy import asarray
import PIL
from PIL import Image

## FUNCTION

In [24]:
def myconv2D(img,m,filters,s):
    image_obj=Image.open(img)
    data=asarray(image_obj)
    l,b,d=data.shape
    flt=asarray(filters)
    n,r,c=flt.shape
    if m == n//d:
        if d==1:
            out = np.zeros((n,((l-r)//s)+1,((b-c)//s)+1))
            for curr_f in range(n):
                curr_y = out_y = 0
                while curr_y + r <= l:
                    curr_x = out_x = 0
                    while curr_x + c <= b:
                        #out[curr_f, out_y, out_x] = np.sum(flt[curr_f] * data[curr_y:curr_y+r, curr_x:curr_x+c,curr_f%d])
                        out[curr_f, out_y, out_x] = np.sum(flt * data[curr_y:curr_y+r, curr_x:curr_x+c])
                        curr_x += s
                        out_x += 1
                    curr_y += s
                    out_y += 1
            result=out
        else:
            out = np.zeros((n,((l-r)//s)+1,((b-c)//s)+1))
            for curr_f in range(n):
                curr_y = out_y = 0
                while curr_y + r <= l:
                    curr_x = out_x = 0
                    while curr_x + c <= b:
                        out[curr_f, out_y, out_x] = np.sum(flt[curr_f] * data[curr_y:curr_y+r, curr_x:curr_x+c,curr_f%d])
                        #out[curr_f, out_y, out_x] = np.sum(flt * data[curr_y:curr_y+r, curr_x:curr_x+c])
                        curr_x += s
                        out_x += 1
                    curr_y += s
                    out_y += 1
            result=np.zeros((m,((l-r)//s)+1,((b-c)//s)+1,d))
            for f in range(m):
                for i in range(((l-r)//s)+1):
                    for j in range(((b-c)//s)+1):
                        for k in range(d):
                            result[f,i,j,k]=out[f*d+k,i,j]
        return result
    else:
        return ["ERROR"]

## INPUT:

In [25]:
fltr=[[[1,0,1],
       [1,1,1],
       [1,0,1]],
      
      [[0,0,1],
       [1,1,1],
       [1,0,1]],
      
      [[1,0,0],
       [1,1,1],
       [1,0,1]],
      
      [[1,0,1],
       [0,1,0],
       [1,0,1]],
      
      [[1,0,1],
       [1,0,1],
       [1,0,1]],
      
      [[1,0,1],
       [0,0,0],
       [1,0,1]]]

In [30]:
r=myconv2D("dog.jpg",2,fltr,1)

## OUTPUT:

In [31]:
print(r.shape)

(2, 424, 638, 3)


In [32]:
print(r[0])

[[[1672. 1424. 1306.]
  [1678. 1431. 1312.]
  [1683. 1437. 1316.]
  ...
  [1587. 1357. 1168.]
  [1588. 1358. 1164.]
  [1586. 1357. 1158.]]

 [[1663. 1419. 1302.]
  [1673. 1428. 1310.]
  [1681. 1436. 1317.]
  ...
  [1584. 1353. 1163.]
  [1580. 1351. 1155.]
  [1576. 1349. 1146.]]

 [[1666. 1424. 1312.]
  [1671. 1428. 1314.]
  [1677. 1433. 1319.]
  ...
  [1575. 1344. 1155.]
  [1570. 1342. 1143.]
  [1570. 1345. 1137.]]

 ...

 [[ 427.  251.  206.]
  [ 440.  263.  220.]
  [ 446.  268.  225.]
  ...
  [ 537.  295.  196.]
  [ 549.  297.  205.]
  [ 545.  285.  202.]]

 [[ 426.  240.  194.]
  [ 443.  254.  209.]
  [ 451.  262.  216.]
  ...
  [ 492.  257.  154.]
  [ 494.  248.  156.]
  [ 492.  240.  147.]]

 [[ 417.  225.  181.]
  [ 431.  236.  193.]
  [ 438.  242.  199.]
  ...
  [ 451.  225.  127.]
  [ 448.  211.  124.]
  [ 445.  209.  111.]]]


In [33]:
print(r[1])

[[[1195. 1427.  872.]
  [1198. 1433.  875.]
  [1202. 1436.  877.]
  ...
  [1133. 1355.  778.]
  [1134. 1358.  775.]
  [1133. 1357.  772.]]

 [[1189. 1420.  872.]
  [1195. 1429.  877.]
  [1201. 1434.  880.]
  ...
  [1131. 1353.  775.]
  [1128. 1352.  771.]
  [1126. 1350.  765.]]

 [[1191. 1423.  874.]
  [1194. 1427.  876.]
  [1198. 1431.  878.]
  ...
  [1125. 1347.  769.]
  [1121. 1345.  762.]
  [1122. 1346.  760.]]

 ...

 [[ 301.  246.  132.]
  [ 309.  256.  137.]
  [ 313.  261.  135.]
  ...
  [ 381.  290.  129.]
  [ 389.  293.  130.]
  [ 383.  290.  122.]]

 [[ 305.  240.  133.]
  [ 317.  253.  141.]
  [ 322.  262.  142.]
  ...
  [ 351.  254.  104.]
  [ 351.  254.  106.]
  [ 348.  256.  102.]]

 [[ 298.  225.  126.]
  [ 309.  237.  135.]
  [ 315.  247.  137.]
  ...
  [ 331.  231.  100.]
  [ 330.  226.   99.]
  [ 327.  226.   95.]]]
